common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  min_messages: warning

development:
  database: foodie_development
  username:
  password:
  <<: *common

test:
  database: foodie_test
  <<: *common

